version: "3.9"

networks: 
  keycloak:
    name: keycloak
    attachable: true    

volumes:
  postgres_data:

services:
  postgres:
      image: postgres:16.2
      container_name: postgres
      hostname: postgres
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data
      env_file:
        - .env
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - 5432:5432
      networks:
       - keycloak
        
  keycloak:
    image: keycloak/keycloak:26.0
    container_name: keycloak
    env_file:
      - .env
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_EXTRA_ARGS_PREPENDED: ${KEYCLOAK_EXTRA_ARGS_PREPENDED}
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      JDBC_PARAMS: "ssl=true"
    command:
      - start-dev
      - --db=postgres
      - --db-url=jdbc:postgresql://postgres/keycloak
      - --db-username=${POSTGRES_USER}
      - --db-password=${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - keycloak

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - 80:80
    networks:
      - keycloak
    volumes: 
      - ./nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf
