---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to sources list
  copy:
    content: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
    dest: /etc/apt/sources.list.d/docker.list

- name: Update apt cache after adding Docker repository
  apt:
    update_cache: yes

- name: Install Docker Engine and related packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to the docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Change permissions for Docker socket
  become: true
  block:
    - name: Set mode for Docker socket
      file:
        path: /var/run/docker.sock
        mode: '0666'

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes